### ISSUE TITLE
fatal error: checkptr: unsafe pointer conversion

### ISSUE THREAD

**Issue by andrewkroh** [elastic/gosigar#138]
Under Go 1.14.4 with the race detector running gosigar fails at

https://github.com/elastic/gosigar/blob/5603641f92c915f979e2eff931fbfd74fa333fb9/sigar_util.go#L10

```
=== RUN   TestFetch
fatal error: checkptr: unsafe pointer conversion

goroutine 50 [running]:
runtime.throw(0x48dfb0e, 0x23)
	/Users/akroh/.gvm/versions/go1.14.4.darwin.amd64/src/runtime/panic.go:1116 +0x72 fp=0xc00016b7c8 sp=0xc00016b798 pc=0x4036fd2
runtime.checkptrAlignment(0xc000652458, 0x4819a40, 0x1)
	/Users/akroh/.gvm/versions/go1.14.4.darwin.amd64/src/runtime/checkptr.go:20 +0xc9 fp=0xc00016b7f8 sp=0xc00016b7c8 pc=0x4008e39
github.com/elastic/gosigar.bytePtrToString(0xc000652458, 0x4dbe04f, 0x1)
	/Users/akroh/go/pkg/mod/github.com/elastic/gosigar@v0.10.5/sigar_util.go:10 +0x52 fp=0xc00016b850 sp=0xc00016b7f8 pc=0x4728c12
github.com/elastic/gosigar.(*FileSystemList).Get(0xc00016b9a8, 0x0, 0x0)
	/Users/akroh/go/pkg/mod/github.com/elastic/gosigar@v0.10.5/sigar_darwin.go:183 +0x1e5 fp=0xc00016b950 sp=0xc00016b850 pc=0x4728ea5
github.com/elastic/beats/v7/metricbeat/module/system/filesystem.GetFileSystemList(0x4757d17, 0xc00050a780, 0xc0000bcac0, 0x1, 0x1)
	/Users/akroh/go/src/github.com/elastic/beats/metricbeat/module/system/filesystem/helper.go:55 +0x4e fp=0xc00016b9d0 sp=0xc00016b950 pc=0x475923e
github.com/elastic/beats/v7/metricbeat/module/system/filesystem.(*MetricSet).Fetch(0xc000640a20, 0x49d00e0, 0xc0006171d0, 0x400cfea, 0x486b620)
```

**Comment by andrewkroh** [comment]
One temporary fix would be to annotate the function with `//go:nocheckptr` (thanks @adriansr).

**Comment by andrewkroh** [comment]
Running the `go test -gcflags=-d=checkptr ./...` will reproduce the error.

**Comment by andrewkroh** [comment]
Fixed by https://github.com/elastic/gosigar/pull/141 according to the PR description.

It does not reproduce for me with Go 1.22.2 under darwin/arm64.
